src/Gib/WebBundle/Entity/Gemstone.php
<?php
namespace Gib\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="gemstone")
 */
class Gemstone extends ImageEntity
{

    /**
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    protected $reference;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    protected $name;

    /**
     * @ORM\ManyToOne(targetEntity="Shape")
     * @ORM\JoinColumn(name="shape_id", referencedColumnName="id")
     */
    protected $shape;

    /**
     * @ORM\ManyToOne(targetEntity="Cut")
     * @ORM\JoinColumn(name="cut_id", referencedColumnName="id", nullable=true)
     */
    protected $cut;

    /**
     * @ORM\ManyToOne(targetEntity="Colour")
     * @ORM\JoinColumn(name="colour_id", referencedColumnName="id")
     */
    protected $colour;

    /**
     * @ORM\ManyToOne(targetEntity="Purity")
     * @ORM\JoinColumn(name="purity_id", referencedColumnName="id")
     */
    protected $purity;

    /**
     * @ORM\ManyToOne(targetEntity="Stone")
     * @ORM\JoinColumn(name="stone_id", referencedColumnName="id")
     */
    protected $stone;

    /**
     * @ORM\Column(type="string", length=25)
     */
    protected $size;

    /**
     * @ORM\Column(type="float")
     */
    protected $weight;

    /**
     * @ORM\Column(type="float")
     */
    protected $price;

    /**
     * @ORM\OneToMany(targetEntity="ArticleGemstone", mappedBy="gemstone")
     */
    protected $articles;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $enabled;

    public function __construct() {
        $this->articles = new ArrayCollection();
        $this->enabled = false;
    }

    public function __toString() {
        return "$this->name ($this->colour, $this->purity, $this->shape, $this->size)";
    }

    /**
     * @ORM\PrePersist()
     */
    public function preSave() {
        $this->generateId();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Gemstone
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set shape
     *
     * @param \Gib\WebBundle\Entity\Shape $shape
     * @return Gemstone
     */
    public function setShape(\Gib\WebBundle\Entity\Shape $shape = null)
    {
        $this->shape = $shape;

        return $this;
    }

    /**
     * Get shape
     *
     * @return \Gib\WebBundle\Entity\Shape
     */
    public function getShape()
    {
        return $this->shape;
    }

    /**
     * Set colour
     *
     * @param \Gib\WebBundle\Entity\Colour $colour
     * @return Gemstone
     */
    public function setColour(\Gib\WebBundle\Entity\Colour $colour = null)
    {
        $this->colour = $colour;

        return $this;
    }

    /**
     * Get colour
     *
     * @return \Gib\WebBundle\Entity\Colour
     */
    public function getColour()
    {
        return $this->colour;
    }

    /**
     * Set purity
     *
     * @param \Gib\WebBundle\Entity\Purity $purity
     * @return Gemstone
     */
    public function setPurity(\Gib\WebBundle\Entity\Purity $purity = null)
    {
        $this->purity = $purity;

        return $this;
    }

    /**
     * Get purity
     *
     * @return \Gib\WebBundle\Entity\Purity
     */
    public function getPurity()
    {
        return $this->purity;
    }

    public function setSize($size)
    {
        $this->size = $size;
        return $this;
    }

    public function getSize()
    {
        return $this->size;
    }

    /**
     * Set getE
     *
     * @param float $price
     * @return Alloy
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set price
     *
     * @param float $price
     * @return Alloy
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * Get Weight
     *
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Add articles
     *
     * @param \Gib\WebBundle\Entity\ArticleGemstone $articles
     * @return Gemstone
     */
    public function addArticle(\Gib\WebBundle\Entity\ArticleGemstone $articles)
    {
        $this->articles[] = $articles;

        return $this;
    }

    /**
     * Remove articles
     *
     * @param \Gib\WebBundle\Entity\ArticleGemstone $articles
     */
    public function removeArticle(\Gib\WebBundle\Entity\ArticleGemstone $articles)
    {
        $this->articles->removeSymbol($articles);
    }

    /**
     * Get articles
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Gemstone
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Gemstone
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set id
     *
     * @param string $id
     * @return Gemstone
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getExpectedPrice() {
        return $this->price;

    }

    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;
        return $this;
    }

    public function isEnabled() {
        return $this->enabled;
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        $this->generateId();
        return $this->id;
    }

    public function generateId()
    {
        if ($this->id === null) {
            $this->id = uniqid();
        }
        return $this->id;
    }

    public function generateFilename()
    {
        return $this->generateId();
    }

    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Set reference
     *
     * @param integer $reference
     * @return Gemstone
     */
    public function setReference($reference)
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * Get reference
     *
     * @return integer
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpdate(){
        if ($this->reference == 0) {
            $this->reference = $this->id;
        }
    }

    /**
     * Set stone
     *
     * @param \Gib\WebBundle\Entity\Stone $stone
     * @return Gemstone
     */
    public function setStone(\Gib\WebBundle\Entity\Stone $stone = null)
    {
        $this->stone = $stone;
    
        return $this;
    }

    /**
     * Get stone
     *
     * @return \Gib\WebBundle\Entity\Stone 
     */
    public function getStone()
    {
        return $this->stone;
    }

    /**
     * Set cut
     *
     * @param \Gib\WebBundle\Entity\Cut $cut
     * @return Gemstone
     */
    public function setCut(\Gib\WebBundle\Entity\Cut $cut = null)
    {
        $this->cut = $cut;
    
        return $this;
    }

    /**
     * Get cut
     *
     * @return \Gib\WebBundle\Entity\Cut 
     */
    public function getCut()
    {
        return $this->cut;
    }
}

src/Gib/WebBundle/Resources/views/Admin/checkPrices.html.twig
<html>
    <head>
    </head>
	<body>
        <h1>Alloys</h1>
        <ul>
            {% for alloy in alloys %} 
            <li>
                {{ alloy.name }}: {{ alloy.price }}€ &lt; {{ alloy.expectedPrice }}€
            </li>
            {% endfor %}
        </ul>
        <h1>Articles</h1>
        <ul>
            {% for article in articles %} 
            <li>
                {{ article.name }}: {{ article.price }}€ &lt; {{ article.expectedPrice }}€
            </li>
            {% endfor %}
        </ul>
	</body>
	
</html>

src/Gib/WebBundle/Resources/views/Admin/image_field.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
	{% if object.image %}
        <img src="/upl/t{{ object.image }}" style="height:32px;display: block;margin: auto;">
    {% else %}
    	<img src="/img/NULL.png" style="height:32px;display: block;margin: auto;">
    {% endif %}
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/mass_field.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
    <div>
        <i>{{ object.name }}</i> 
    </div>
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/money_conditional_field.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
	<div style="text-align: right">
		{% if object.expectedPrice < object.price or object.price <= 0%}
			{{ object.expectedPrice | round(2, 'ceil')}} <b>€</b>
		{% else %}
	        <b style="color:red">{{ object.expectedPrice | round(2, 'ceil')}} €</b>
	    {% endif %}
    </div>
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/money_conditional_field_kilo.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
	<div style="text-align: right">
		{% if object.expectedPrice > 0.1 %}
			{% if object.expectedPrice < object.price or object.price <= 0%}
				{{ object.expectedPrice | round(2, 'ceil')}} <b>€ / g</b>
			{% else %}
		        <b style="color:red">{{ object.expectedPrice | round(2, 'ceil') }} <b>€ / g</b></b>
		    {% endif %}
		{% elseif object.expectedPrice > 0.0001 %}
			{% if object.expectedPrice < object.price or object.price <= 0%}
				{{ (object.expectedPrice * 1000) | round(2, 'ceil') }} <b>€ / kg</b>
			{% else %}
		        <b style="color:red">{{ (object.expectedPrice * 1000) | round(2, 'ceil') }} <b>€ / kg</b></b>
		    {% endif %}
		{% elseif object.expectedPrice > 0 %}
			{% if object.expectedPrice < object.price or object.price <= 0%}
				{{ (object.expectedPrice * 1000000) | round(2, 'ceil') }} <b>€ / t</b>
			{% else %}
		        <b style="color:red">{{ (object.expectedPrice * 1000000) | round(2, 'ceil') }} <b>€ / t</b></b>
		    {% endif %}t
		{% else %}
		    ---
		{% endif %}
	</div>
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/money_field.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
	<div style="text-align: right">
		{% if object.price > 0 %}
			{{ object.price | round(2, 'ceil') }} <b>€</b>
		{% else %}
		    ---
		{% endif %}
	</div>
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/money_field_kilo.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field%}
	<div style="text-align: right">
		{% if object.price > 0.1 %}
			{{ object.price | round(2, 'ceil') }} <b>€ / g</b>
		{% elseif object.price > 0.0001 %}
			{{ (object.price * 1000) | round(2, 'ceil') }} <b>€ / kg</b>
		{% elseif object.price > 0 %}
			{{ (object.price * 1000000) | round(2, 'ceil') }} <b>€ / t</b>
		{% else %}
		    ---
		{% endif %}
	</div>
{% endblock %}

src/Gib/WebBundle/Resources/views/Admin/piecekind.html.twig
<html>
	<head>
		<title>
			Tipos de pieza
		</title>
		<style>
			th, td {
				border-style: solid;
				border-width: 1px;
				margin: 0;
				padding: 5px 20px;
			}
		</style>
		<script src="http://localhost:8000/images/piecekinds/527f855a5df45.js" type="text/javascript"></script>
	</head>
	<body>
		<table>

			<a href="/admin/2/piecekind/new">Crear nuevo</a>
			<thead>
				<tr>
					<th>ID</th><th>Nombre</th><th>Imagen</th><th>Fecha de creacíon</th><th>Ultima modificacion</th><th>Eliminado?</th>
				</tr>
			</thead>
			<tbody>
				{% for piecekind in piecekinds %}
					<tr>
						<td>{{ piecekind.id }}</td>
						<td>{{ piecekind.name }}</td>
						<td>{{ piecekind.image }}</td>
						<td>{{ piecekind.createdAt|date("Y/m/d") }}</td>
						<td>{{ piecekind.modifiedAt|date("Y/m/d") }}</td>
						{% if piecekind.deletedAt|date("Y/m/d") %}
							<td></td>
						{% else %}
							<td>X</td>
						{% endif %}
					</tr>
			    {% endfor %}
			</tbody>
			<img src="http://localhost:8000/images/piecekinds/527f855a5df45.pasdasd" />
		</table>
	</body>
</html>

src/Gib/WebBundle/Resources/views/Admin/piecekindNew.html.twig
<html>
	<head>
		<title>
			Tipos de pieza
		</title>
	</head>
	<body>
		<table>

			{% for flashMessage in app.session.flashbag.get('error') %}
			    <div class="flash-notice">
			        {{ flashMessage }}
			    </div>
			{% endfor %}
			<form method="POST" action="/api/piecekind/" enctype="multipart/form-data">
				<input type="text" name="name"  placeholder="nombre"><br>
				<input type="file" name="image" placeholder="imagen">
				<input type="submit" value="Crear">
			</form>
		</table>
	</body>
</html>

src/Gib/WebBundle/Resources/views/Admin/refresh.html.twig
<html>
	<head>
		{% block css %}
            {% stylesheets filter="scss" output="css/style.css"
                '@GibWebBundle/Resources/public/scss/normalize.scss'
                '@GibWebBundle/Resources/public/scss/style.scss'
                '@GibWebBundle/Resources/public/scss/jquery.galleryview-3.0-dev.scss'
            %}
                <link rel="stylesheet" href="{{ asset_url }}"></link>
            {% endstylesheets %}
        {% endblock %}
        {% block js %}
            {% javascripts output="js/javascript.js"
                '@GibWebBundle/Resources/public/js/navi.js'
                '@GibWebBundle/Resources/public/js/jQuery.js'
                '@GibWebBundle/Resources/public/js/jquery.timers-1.2.js'
                '@GibWebBundle/Resources/public/js/jquery.easing.1.3.js'
                '@GibWebBundle/Resources/public/js/jquery.galleryview-3.0-dev.js'
                '@GibWebBundle/Resources/public/js/modernizr.custom.js'
                '@GibWebBundle/Resources/public/js/jquery.dlmenu.js'
            %}
                <script src="{{ asset_url }}" type="text/javascript" charset="utf-8"></script>
            {% endjavascripts %}
        {% endblock %}
        <style type="text/css">
        	.money {
        		text-align: right;
        		vertical-align: middle;
        	}
        </style>
	</head>
	<body>

		<div class="row">
			<div class="large-12">
				<h3>Metales</h3>
				<table>
					<thead>
						<td>Metal</td>
						<td>Símbolo</td>
						<td>Precio viejo</td>
						<td>Precio nuevo</td>
					</thead>
					<tbody>
						<tr>
							<td>{{ symbols[0].name }}</td>
							<td>{{ symbols[0].symbol }}</td>
							<td class="money">{{ symbols[1]|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% if symbols[1] > symbols[0].price %}
								<td class="money" style="color:red">{{ symbols[0].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% elseif symbols[1] < symbols[0].price %}
								<td class="money" style="color:green">{{ symbols[0].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% else %}
								<td class="money"><b>{{ symbols[0].price|round(2, 'ceil')|number_format(2) }} €/g</b></td>
							{% endif %}
						</tr>

						<tr>
							<td>{{ symbols[2].name }}</td>
							<td>{{ symbols[2].symbol }}</td>
							<td class="money">{{ symbols[3]|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% if symbols[3] > symbols[2].price %}
								<td class="money" style="color:red">{{ symbols[2].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% elseif symbols[3] < symbols[2].price %}
								<td class="money" style="color:green">{{ symbols[2].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% else %}
								<td class="money"><b>{{ symbols[2].price|round(2, 'ceil')|number_format(2) }} €/g</b></td>
							{% endif %}
						</tr>

						<tr>
							<td>{{ symbols[4].name }}</td>
							<td>{{ symbols[4].symbol }}</td>
							<td class="money">{{ symbols[5]|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% if symbols[5] > symbols[4].price %}
								<td class="money" style="color:red">{{ symbols[4].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% elseif symbols[5] < symbols[4].price %}
								<td class="money" style="color:green">{{ symbols[4].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% else %}
								<td class="money"><b>{{ symbols[4].price|round(2, 'ceil')|number_format(2) }} €/g</b></td>
							{% endif %}
						</tr>

						<tr>
							<td>{{ symbols[6].name }}</td>
							<td>{{ symbols[6].symbol }}</td>
							<td class="money">{{ symbols[7]|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% if symbols[7] > symbols[6].price %}
								<td class="money" style="color:red">{{ symbols[6].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% elseif symbols[7] < symbols[6].price %}
								<td class="money" style="color:green">{{ symbols[6].price|round(2, 'ceil')|number_format(2) }} €/g</td>
							{% else %}
								<td class="money"><b>{{ symbols[6].price|round(2, 'ceil')|number_format(2) }} €/g</b></td>
							{% endif %}
						</tr>

					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
        	<div class="large-12">
        		<h3>Aleaciones</h3>
        		<table>
					<thead>
						<tr>
							<td>Ref.</td>
							<td>Nombre</td>
							<td>Precio</td>
							<td>Precio recomendado</td>
							<td></td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						{% for alloy in alloys %}
					        <tr>
					        	<td>{{ alloy.reference }}</td>
					        	<td>{{ alloy.name }}</td>
					        	<td class="money">{{ alloy.price|number_format(2) }} €</td>
					        	<td class="money">{{ alloy.expectedPrice|number_format(2) }} €</td>
					        	<td><a href="/admin/2/alloy/disable/{{ alloy.id }}">Deshabilitar</a></td>
					        	<td><a href="/admin/2/alloy/reset/{{ alloy.id }}">Cambiar precio a {{ alloy.expectedPrice }}</a></td>
					        </tr>
					    {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
        	<div class="large-12">
        		<h3>Articulos</h3>
        		<table>
					<thead>
						<tr>
							<td>Ref.</td>
							<td>Nombre</td>
							<td>Precio</td>
							<td>Precio recomendado</td>
							<td></td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						{% for article in articles %}
					        <tr>
					        	<td>{{ article.reference }}</td>
					        	<td>{{ article.name }}</td>
					        	<td class="money">{{ article.price|number_format(2) }} €</td>
					        	<td class="money">{{ article.expectedPrice|number_format(2) }} €</td>
					        	<td><a href="/admin/2/article/disable/{{ article.id }}">Deshabilitar</a></td>
					        	<td><a href="/admin/2/article/reset/{{ article.id }}">Cambiar precio a {{ article.expectedPrice }}</a></td>
					        </tr>
					    {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</body>
</html>